# PYOXIDIZER_BUILD_FORCE_GIT_SOURCE is set throughout this file to prevent
# pyoxidizer's build.rs from writing the filesystem path to the Git checkout
# in the built binary. With the filesystem path embedded in the binary,
# pyoxidizer will probe for that path at run-time and will attempt to use
# it for the location of the pyembed crate. With the filesystem path not
# set, pyoxidizer will use the canonical github.com repository for any Git
# references.
#
# For the spot tests, we purposefully perform these on separate jobs
# because we don't want a Python or Rust install from the build environment
# to impact the testing.

on:
  push:
  pull_request:
  schedule:
    - cron: '13 15 * * *'
jobs:
  pyoxidizer-exes:
    uses: ./.github/workflows/build-exe.yml
    with:
      bin: pyoxidizer
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  pyoxidizer-linux-x86_64-wheel:
    needs:
      - pyoxidizer-exes
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2

      - name: Download Executable
        uses: actions/download-artifact@v2
        with:
          name: exe-pyoxidizer-x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl/release/

      - name: Build Wheel
        run: |
          chmod +x target/x86_64-unknown-linux-musl/release/pyoxidizer
          target/x86_64-unknown-linux-musl/release/pyoxidizer build --release wheel_linux
          mkdir -p wheelhouse
          mv build/*/*/*/*.whl wheelhouse/

      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: pyoxidizer-wheels
          path: wheelhouse

  pyoxidizer-linux-x86_64-bin-check:
    needs:
      - pyoxidizer-exes
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Install musl compiler
        run: |
          sudo apt install -y --no-install-recommends musl-tools

      - name: Download Executable
        uses: actions/download-artifact@v2
        with:
          name: exe-pyoxidizer-x86_64-unknown-linux-musl

      - name: Spot Test (Native Build)
        run: |
          chmod +x pyoxidizer
          ./pyoxidizer init-config-file myapp
          ./pyoxidizer build --path myapp

      # TODO disabled because of duplicate ffi_type_double, etc symbol failures.
      #- name: Spot Test (musl Cross)
      #  run: |
      #    ./pyoxidizer build --path myapp --target-triple x86_64-unknown-linux-musl

  pyoxidizer-macos-exe:
    needs:
      - pyoxidizer-exes
    strategy:
      fail-fast: false
      matrix:
        target_triple:
          - 'aarch64-apple-darwin'
          - 'x86_64-apple-darwin'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Download Executable
        uses: actions/download-artifact@v2
        with:
          name: exe-pyoxidizer-${{ matrix.target_triple }}
          path: dist/${{ matrix.target_triple }}/

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: pyoxidizer-macos_exes
          path: |
            dist/*/*

  # We need a separate wheel job for macOS because we need a host pyoxidizer to generate
  # the wheel for cross-compiles.
  pyoxidizer-macos-wheel:
    strategy:
      fail-fast: false
      matrix:
        config:
          - target_triple: 'aarch64-apple-darwin'
            wheel_target: 'wheel_macos_aarch64'
          - target_triple: 'x86_64-apple-darwin'
            wheel_target: 'wheel_macos_x86_64'
    needs:
      - pyoxidizer-exes
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2

      - name: Download Linux exe
        uses: actions/download-artifact@v3
        with:
          name: exe-pyoxidizer-x86_64-unknown-linux-musl
          path: dist

      - name: Download macOS Exes
        uses: actions/download-artifact@v3
        with:
          name: exe-pyoxidizer-${{ matrix.config.target_triple }}
          path: target/${{ matrix.config.target_triple }}/release/

      - name: Build Wheel
        run: |
          chmod +x dist/pyoxidizer
          dist/pyoxidizer build --release ${{ matrix.config.wheel_target }}

          mkdir wheelhouse
          mv build/*/*/*/*.whl wheelhouse/

      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: pyoxidizer-wheels
          path: wheelhouse

  pyoxidizer-macos-universal-exe-check:
    needs:
      - pyoxidizer-exes
    runs-on: 'macos-10.15'
    steps:
      - name: Download macOS Executable
        uses: actions/download-artifact@v3
        with:
          name: exe-pyoxidizer-macos-universal
          path: macos-universal

      - name: Spot Test (Native Build)
        run: |
          find . -type f
          mv macos-universal/pyoxidizer .
          chmod +x pyoxidizer
          ./pyoxidizer init-config-file myapp
          ./pyoxidizer build --path myapp

      - name: Spot Test (aarch64 Cross Build)
        env:
          # The default SDK is 10.15 and the 11.x SDK isn't in a default search path.
          # So we need to point pyoxidizer at a more modern SDK.
          SDKROOT: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk
        run: |
          ./pyoxidizer build --path myapp --target-triple aarch64-apple-darwin

  pyoxidizer-macos-dmg:
    needs:
      - pyoxidizer-macos-exe
    runs-on: 'macos-10.15'
    env:
      IN_CI: '1'
    steps:
      - uses: actions/checkout@v2

      - name: Download CLI exes
        uses: actions/download-artifact@v3
        with:
          name: pyoxidizer-macos_exes
          path: dist

      - name: Build DMG
        run: |
          scripts/make-dmg.sh

      - name: Upload DMG
        uses: actions/upload-artifact@v3
        with:
          name: pyoxidizer-macos_dmg
          path: |
            PyOxidizer.dmg

  pyoxidizer-windows-wheel:
    needs:
      - pyoxidizer-exes
    strategy:
      fail-fast: false
      matrix:
        config:
          - target_triple: 'i686-pc-windows-msvc'
            wheel_target: 'wheel_windows_x86'
          - target_triple: 'x86_64-pc-windows-msvc'
            wheel_target: 'wheel_windows_x86_64'
    runs-on: 'windows-2022'
    steps:
      - uses: actions/checkout@v2

      - name: Download Executable
        uses: actions/download-artifact@v3
        with:
          name: exe-pyoxidizer-${{ matrix.config.target_triple }}
          path: target/${{ matrix.config.target_triple }}/release/

      - name: Build Wheel
        run: |
          target/${{ matrix.config.target_triple }}/release/pyoxidizer.exe build --release ${{ matrix.config.wheel_target }}
          New-Item -ItemType "directory" -Name "wheelhouse"
          move build/*/*/*/*.whl wheelhouse/

      - name: Upload Wheel
        uses: actions/upload-artifact@v3
        with:
          name: pyoxidizer-wheels
          path: wheelhouse

  pyoxidizer-windows-exe-check:
    strategy:
      fail-fast: false
      matrix:
        config:
          - host_triple: 'i686-pc-windows-msvc'
            target_triple: 'x86_64-pc-windows-msvc'
          - host_triple: 'x86_64-pc-windows-msvc'
            target_triple: 'i686-pc-windows-msvc'
    needs:
      - pyoxidizer-exes
    runs-on: 'windows-2019'
    steps:
      - name: Download Windows Executable
        uses: actions/download-artifact@v3
        with:
          name: exe-pyoxidizer-i686-pc-windows-msvc
          path: i686-pc-windows-msvc/

      - name: Download Windows Executable
        uses: actions/download-artifact@v3
        with:
          name: exe-pyoxidizer-x86_64-pc-windows-msvc
          path: x86_64-pc-windows-msvc/

      - name: Spot Test (Native Build)
        run: |
          ${{ matrix.config.host_triple }}/pyoxidizer.exe init-config-file myapp
          ${{ matrix.config.host_triple }}/pyoxidizer.exe build --path myapp

      - name: Spot Test (Cross-Compile Build)
        run: |
          ${{ matrix.config.host_triple }}/pyoxidizer.exe build --path myapp --target-triple ${{ matrix.config.target_triple }}

  pyoxidizer-windows-installer:
    needs:
      - pyoxidizer-exes
    runs-on: 'windows-2019'
    env:
      IN_CI: '1'
    steps:
      - uses: actions/checkout@v2

      - name: Download Windows Executable
        uses: actions/download-artifact@v3
        with:
          name: exe-pyoxidizer-i686-pc-windows-msvc
          path: dist/i686-pc-windows-msvc/

      - name: Download Windows Executable
        uses: actions/download-artifact@v3
        with:
          name: exe-pyoxidizer-x86_64-pc-windows-msvc
          path: dist/x86_64-pc-windows-msvc/

      # We can use the built/downloaded pyoxidizer.exe to package itself. Nice.
      # Building the exe installer will build the MSI installers. 2 birds 1 stone.
      - name: Build Installers
        run: |
          dist/x86_64-pc-windows-msvc/pyoxidizer.exe build --var-env IN_CI IN_CI --release --target-triple x86_64-pc-windows-msvc exe_installer
          move build/x86_64-pc-windows-msvc/release/*/*.msi .
          move build/x86_64-pc-windows-msvc/release/*/*.exe .

      - name: Upload installers
        uses: actions/upload-artifact@v3
        with:
          name: pyoxidizer-windows_installers
          path: |
            *.exe
            *.msi

  pyoxidizer-linux-wheels-cross:
    strategy:
      fail-fast: false
      matrix:
        platform: [
          { manylinux: '2010', target: "i686-unknown-linux-musl", image_tag: "i686-musl" },
          { manylinux: '2014', target: "aarch64-unknown-linux-musl", image_tag: "aarch64-musl" },
          { manylinux: '2014', target: "armv7-unknown-linux-musleabihf", image_tag: "armv7-musleabihf" },
        ]
    runs-on: 'ubuntu-20.04'
    container:
      image: docker://messense/rust-musl-cross:${{ matrix.platform.image_tag }}
      env:
        RUSTUP_HOME: /root/.rustup
        CARGO_HOME: /root/.cargo
        CFLAGS_armv7_unknown_linux_musleabihf: -mfpu=vfpv3-d16
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Wheels
        env:
          PYOXIDIZER_BUILD_FORCE_GIT_SOURCE: '1'
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip3 install maturin==0.10.4
          maturin build -m pyoxidizer/Cargo.toml -b bin --no-sdist --release -o dist --target ${{ matrix.platform.target }} --manylinux ${{ matrix.platform.manylinux }}
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: pyoxidizer-wheels
          path: dist
